# Generated by Django 5.2.1 on 2025-05-21 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=256)),
                ('apartment', models.CharField(max_length=50)),
                ('entrance', models.SmallIntegerField(blank=True, null=True)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('intercom', models.SmallIntegerField(blank=True, null=True)),
                ('clarification_to_the_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'basket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BindingType',
            fields=[
                ('binding_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_binding_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'binding_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price_book', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image_path', models.TextField()),
                ('age_limit', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField()),
                ('circulation', models.IntegerField()),
                ('weight', models.SmallIntegerField()),
                ('size', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.SmallIntegerField()),
                ('year_of_publication', models.IntegerField()),
                ('year_of_release', models.IntegerField(blank=True, null=True)),
                ('rating', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('book_series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_book_series', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'book_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 's_books.category_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralsProducts',
            fields=[
                ('general_products_id', models.UUIDField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_punched_sheets', models.SmallIntegerField(blank=True, null=True)),
                ('calculator_bit_size', models.SmallIntegerField(blank=True, null=True)),
                ('number_stapler', models.CharField(blank=True, max_length=10, null=True)),
                ('peculiarity', models.TextField(blank=True, null=True)),
                ('number_staples', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'generals_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.UUIDField(db_default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(db_default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ожидание оплаты', 'Ожидание оплаты'), ('Оплачен', 'Оплачен'), ('Собран', 'Собран'), ('Передан в доставку', 'Передан в доставку'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Отменён', 'Отменён'), ('Возврат', 'Возврат'), ('Завершён', 'Завершён')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperProducts',
            fields=[
                ('paper_products_id', models.UUIDField(primary_key=True, serialize=False)),
                ('number_of_sheets', models.SmallIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('type_of_ruler', models.CharField(blank=True, max_length=50, null=True)),
                ('peculiarity', models.TextField(blank=True, null=True)),
                ('mounting_type', models.CharField(blank=True, max_length=50, null=True)),
                ('calendar_year', models.SmallIntegerField(blank=True, null=True)),
                ('quantity_colors', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(db_default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.TextField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('успешно', 'Успешно'), ('ошибка', 'Ошибка'), ('ожидание', 'Ожидание'), ('возврат', 'Возврат')], default='ожидание', max_length=20)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_publisher', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(max_length=255)),
                ('review_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('stationery_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_stationery', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('date_of_receipt', models.DateTimeField()),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('age_limit', models.CharField(blank=True, max_length=3, null=True)),
                ('material_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'stationery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('storage_type_id', models.UUIDField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_branches', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('peculiarity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'storage_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_subcategory', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoryStationery',
            fields=[
                ('subcategory_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name_subcategory', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subcategory_stationery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscriptions_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wishlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WritingMaterials',
            fields=[
                ('writing_materials_id', models.UUIDField(primary_key=True, serialize=False)),
                ('inc_color', models.CharField(blank=True, max_length=50, null=True)),
                ('inc_base', models.CharField(blank=True, max_length=50, null=True)),
                ('pen_thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('peculiarity', models.TextField(blank=True, null=True)),
                ('quantity_colors', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'writing_materials',
                'managed': False,
            },
        ),
    ]
